name: "BorderlessNPC"
main: tw.mayortw.blnpc.BorderlessNPCPlugin
version: 0.6
description: "無序NPC"
author: "R26"
depend:
    - Citizens
commands:
    blnpc:
        usage: "Usage: /<command> < sethome | clearhome | setrange <range> | clearrange | setdamage <damage> | cleardamage >"
        permission: blnpc.edit
    bltgt:
        usage: |
            Usage: /<command> < addtarget <rule> [duration] | addexclude <rule> [duration] | deltarget <rule> | delexclude <rule> | cleartarget | clearexclude | listtarget | listexclude >
            <rule> can be < type | name | perm>:<rule>
            Example: type:chicken specifies all chicken, name:Steve specifies entities with name Steve
            [duration] specifies the duration of the rule
            Example: 5m10s, 1d6h. Valid units are Y M d h m s
        permission: blnpc.edit
permissions:
    blnpc.edit:
        default: op
