name: "BorderlessNPC"
main: tw.mayortw.blnpc.BorderlessNPCPlugin
version: 0.4
description: "無序NPC"
author: "R26"
depend:
    - Citizens
commands:
    blnpc:
        usage: "Usage: /<command> < sethome | clearhome | setrange <range> | clearrange >"
        permission: blnpc.edit
permissions:
    blnpc.edit:
        default: op
