name: "BorderlessNPC"
main: tw.mayortw.blnpc.BorderlessNPCPlugin
version: 0.2
description: "無序NPC"
author: "R26"
depend:
    - Citizens
commands:
    blnpc:
        usage: "Usage: /<command> sethome"
