name: "BorderlessNPC"
main: tw.mayortw.blnpc.BorderlessNPCPlugin
version: 0.6
description: "無序NPC"
author: "R26"
depend:
    - Citizens
commands:
    blnpc:
        usage: "Usage: /<command> < sethome | clearhome | setrange <range> | clearrange | setdamage <damage> | cleardamage >"
        permission: blnpc.edit
    bltgt:
        usage: |
            Usage: /<command> < addtarget <rule> | deltarget <rule> | addexclude <rule> | delexclude <rule> | listtarget | listexclude >
            Where <rule> can be type:<entity_type>, name:<entity_name>, or perm:<permission>
        permission: blnpc.edit
permissions:
    blnpc.edit:
        default: op
