name: "BorderlessNPC"
main: tw.mayortw.blnpc.BorderlessNPCPlugin
version: 0.5.1
description: "無序NPC"
author: "R26"
depend:
    - Citizens
commands:
    blnpc:
        usage: "Usage: /<command> < sethome | clearhome | setrange <range> | clearrange | setdamage <damage> | cleardamage >"
        permission: blnpc.edit
permissions:
    blnpc.edit:
        default: op
